{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Training Session"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:13:17.193500Z",
     "start_time": "2018-07-12T16:13:17.190703Z"
    }
   },
   "outputs": [],
   "source": [
    "import pickle\n",
    "\n",
    "from build_vocab import *\n",
    "from build_answers import *\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:13:18.372968Z",
     "start_time": "2018-07-12T16:13:18.361250Z"
    }
   },
   "outputs": [],
   "source": [
    "# train2014\n",
    "answers_path = '/home/ubuntu/dotCuda/notebook/answers.pkl'\n",
    "with open(answers_path, 'rb') as f:\n",
    "    answers = pickle.load(f)\n",
    "\n",
    "vocab_path = '../../dotCuda/notebook/vocab.pkl'\n",
    "with open(vocab_path, 'rb') as f:\n",
    "    vocab = pickle.load(f)\n",
    "    \n",
    "# val2014\n",
    "answers_path = '/home/ubuntu/dotCuda/notebook/valanswers.pkl'\n",
    "with open(answers_path, 'rb') as f:\n",
    "    valanswers = pickle.load(f)\n",
    "\n",
    "vocab_path = '../../dotCuda/notebook/valvocab.pkl'\n",
    "with open(vocab_path, 'rb') as f:\n",
    "    valvocab = pickle.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:13:43.511609Z",
     "start_time": "2018-07-12T16:13:20.347389Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loading VQA annotations and questions into memory...\n",
      "0:00:09.533576\n",
      "creating index...\n",
      "index created!\n",
      "loading VQA annotations and questions into memory...\n",
      "0:00:10.181387\n",
      "creating index...\n",
      "index created!\n"
     ]
    }
   ],
   "source": [
    "from dataset import *\n",
    "\n",
    "train_dataset = COCODataset(vocab=vocab, answers=answers)\n",
    "val_dataset = COCODataset(vocab=valvocab, answers=valanswers)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-10T12:30:16.457121Z",
     "start_time": "2018-07-10T12:30:16.454260Z"
    }
   },
   "source": [
    "### Network Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:13:48.091307Z",
     "start_time": "2018-07-12T16:13:48.088658Z"
    }
   },
   "outputs": [],
   "source": [
    "# import network \n",
    "from network_v5b import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T05:45:35.415973Z",
     "start_time": "2018-07-12T05:45:29.726499Z"
    }
   },
   "outputs": [],
   "source": [
    "import torch\n",
    "device = torch.device('cuda')\n",
    "\n",
    "vocab_size = len(vocab)\n",
    "model = ConcatNet(vocab_size).to(device)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Trainer Class"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T05:45:55.903263Z",
     "start_time": "2018-07-12T05:45:55.738516Z"
    }
   },
   "outputs": [],
   "source": [
    "# import trainer\n",
    "from trainer import VQATrainer\n",
    "\n",
    "trainer = VQATrainer(model, device)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Train!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T05:49:20.716832Z",
     "start_time": "2018-07-12T05:45:57.382002Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 0 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 8.00637 and accuracy 0.000 in 0.7335s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4f28>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.6977s\n",
      "Epoch 1 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.6122s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9564s\n",
      "Epoch 2 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0234s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9907s\n",
      "Epoch 3 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9401s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 0.9917s\n",
      "Epoch 4 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0094s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0380s\n",
      "Epoch 5 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9355s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8784s\n",
      "Epoch 6 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9974s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0465s\n",
      "Epoch 7 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9474s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0097s\n",
      "Epoch 8 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4f60>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8199s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0375s\n",
      "Epoch 9 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9276s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8734s\n",
      "Epoch 10 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7497s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8472s\n",
      "Epoch 11 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9159s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 1.0161s\n",
      "Epoch 12 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9308s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8806s\n",
      "Epoch 13 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9956s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 0.8727s\n",
      "Epoch 14 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0099s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8684s\n",
      "Epoch 15 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0050s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8675s\n",
      "Epoch 16 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8430s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8554s\n",
      "Epoch 17 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9296s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9033s\n",
      "Epoch 18 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 494, in Client\n",
      "    deliver_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 722, in deliver_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7571s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8984s\n",
      "Epoch 19 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7682s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 1.0212s\n",
      "Epoch 20 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0604425c0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7974s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.9629s\n",
      "Epoch 21 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb060446710>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    ....iteration 1/55470   [loss 7.881940841674805 || acc 2.2534703443302684e-06]\r",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7765s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb062206898>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    ....iteration 1/55470   [loss 8.006941795349121 || acc 0.0]\r",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8616s\n",
      "Epoch 22 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0604429e8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.5954s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 0.8634s\n",
      "Epoch 23 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0297s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 1.0124s\n",
      "Epoch 24 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0247s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 1.0099s\n",
      "Epoch 25 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7769s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 0.8625s\n",
      "Epoch 26 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0195s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8638s\n",
      "Epoch 27 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9578s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8787s\n",
      "Epoch 28 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9540s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8534s\n",
      "Epoch 29 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0281s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0582s\n",
      "Epoch 30 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9103s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8795s\n",
      "Epoch 31 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8455s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9947s\n",
      "Epoch 32 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9596s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0345s\n",
      "Epoch 33 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7510s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8958s\n",
      "Epoch 34 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9233s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8808s\n",
      "Epoch 35 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9069s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8571s\n",
      "Epoch 36 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7974s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8824s\n",
      "Epoch 37 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7474s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8542s\n",
      "Epoch 38 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8395s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8948s\n",
      "Epoch 39 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9437s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.9966s\n",
      "Epoch 40 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8822s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8753s\n",
      "Epoch 41 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8279s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9716s\n",
      "Epoch 42 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9311s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8696s\n",
      "Epoch 43 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7977s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9886s\n",
      "Epoch 44 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8009s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8708s\n",
      "Epoch 45 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8847s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 0.8820s\n",
      "Epoch 46 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9933s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8891s\n",
      "Epoch 47 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7476s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8359s\n",
      "Epoch 48 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb128227780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7570s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8728s\n",
      "Epoch 49 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9380s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8481s\n",
      "Epoch 50 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9157s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8754s\n",
      "Epoch 51 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.6998s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9004s\n",
      "Epoch 52 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9422s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8811s\n",
      "Epoch 53 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7964s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0063s\n",
      "Epoch 54 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4f28>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7305s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8758s\n",
      "Epoch 55 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9655s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0228s\n",
      "Epoch 56 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8449s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9866s\n",
      "Epoch 57 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9646s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8601s\n",
      "Epoch 58 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9237s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0184s\n",
      "Epoch 59 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9155s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8740s\n",
      "Epoch 60 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4fd0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 494, in Client\n",
      "    deliver_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 722, in deliver_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9130s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 1.0419s\n",
      "Epoch 61 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9410s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8692s\n",
      "Epoch 62 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9097s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8769s\n",
      "Epoch 63 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9276s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8659s\n",
      "Epoch 64 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9551s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0299s\n",
      "Epoch 65 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9532s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8652s\n",
      "Epoch 66 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9321s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8363s\n",
      "Epoch 67 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8585s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8886s\n",
      "Epoch 68 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9695s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0061s\n",
      "Epoch 69 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7899s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8640s\n",
      "Epoch 70 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8043s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0210s443302684e-06]\n",
      "Epoch 71 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4f60>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8210s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0362s\n",
      "Epoch 72 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9703s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8762s\n",
      "Epoch 73 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb060442438>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7627s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.00521 and accuracy 0.000 in 0.8815s\n",
      "Epoch 74 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9559s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8889s\n",
      "Epoch 75 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9597s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8777s\n",
      "Epoch 76 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9096s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8839s\n",
      "Epoch 77 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9417s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8749s\n",
      "Epoch 78 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9563s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0497s\n",
      "Epoch 79 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9128s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8421s\n",
      "Epoch 80 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7767s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0010s\n",
      "Epoch 81 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9961s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.9894s\n",
      "Epoch 82 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9899s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 1.0153s\n",
      "Epoch 83 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4f28>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7931s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8930s\n",
      "Epoch 84 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9663s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8780s\n",
      "Epoch 85 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0322s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8799s\n",
      "Epoch 86 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0325s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 6.88107 and accuracy 0.000 in 0.8649s443302684e-06]\n",
      "Epoch 87 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7822s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8298s\n",
      "Epoch 88 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8753s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8820s\n",
      "Epoch 89 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 1.0049s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 1.0006s\n",
      "Epoch 90 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9307s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8692s\n",
      "Epoch 91 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9379s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0459s\n",
      "Epoch 92 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7781s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8759s\n",
      "Epoch 93 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8074s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8825s\n",
      "Epoch 94 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0604422e8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8091s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 1.0135s\n",
      "Epoch 95 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7797s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8608s\n",
      "Epoch 96 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb060442898>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.7888s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8698s\n",
      "Epoch 97 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9603s443302684e-06]\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7faff1fc2320>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 181, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/usr/lib/python3.5/multiprocessing/reduction.py\", line 152, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 0.8538s\n",
      "Epoch 98 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.9344s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 7.00607 and accuracy 0.000 in 1.0148s\n",
      "Epoch 99 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb0622a4f60>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 345, in get\n",
      "    return ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/virtuals/pytorch-cu90-0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/usr/lib/python3.5/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 7.88194 and accuracy 0.000 in 0.8039s443302684e-06]\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 8.00694 and accuracy 0.000 in 0.8359s\n"
     ]
    }
   ],
   "source": [
    "trained_model, statistics = trainer.train(train_dataset, val_dataset, save_every=50, learnrate=10, collate_fn=collate, e_break=1, epoch=100, val_size=9)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:14:02.062512Z",
     "start_time": "2018-07-12T16:14:01.842775Z"
    }
   },
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'train-losslist'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-8-279843732825>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0mtrainer\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstatistics\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstatistic\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 14\u001b[0;31m \u001b[0mtrainer\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplot_over_epoch\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/dotCuda/notebook/trainer.py\u001b[0m in \u001b[0;36mplot_over_epoch\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    226\u001b[0m         \u001b[0;31m# plot in-epoch statistics\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    227\u001b[0m         \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfigure\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 228\u001b[0;31m         \u001b[0mnrow\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstatistics\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'train-losslist'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    229\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnrow\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    230\u001b[0m             \u001b[0;31m# one row per epoch\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'train-losslist'"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZcAAAEICAYAAACTVrmbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvhp/UCwAAIABJREFUeJzt3X+UXWV97/H3B4aJaAwQifyYDInTgyORxQ+ZQbhKtYhOzL0m3tIqLqkBEYqMa7VSu4yLtl4BW/lVf421UNGGrqUI8VqnF2ZsGmP13jaMQ4BABuIEBpgM0EQCUpqa0eP3/rGfgc3pmczkZJ+Zk/B5rXVW9vnu53nOs2ee4cvezz7PVkRgZmZWpINmuwNmZnbgcXIxM7PCObmYmVnhnFzMzKxwTi5mZlY4JxczMyuck4uZmRXOyeUAIulRSefMdj/MzJxczMyscE4uLwOSLpa0VdJOSb2Sjk1xSfq8pO2SnpN0v6QT075lkoYk/bukMUmfyLX3PyTdK+lZSf8i6aTcvk+m8v8uaYukd8z8EZvZbHNyOcBJOhv4C+B9wDHAY8Ctafe7gN8EXg8clso8nfbdDPx+RLwaOBH4QWrvVODrwO8DrwFuBHolzZHUDnwM6Ez1uoBH63yIZtaAnFwOfB8Evh4RGyNiN/Ap4ExJi4FfAq8G3gAoIh6MiCdTvV8CSyTNi4hnImJjil8C3BgRd0VEOSJWA7uBM4AyMCfVOyQiHo2Ih2fqQM2scTi5HPiOJTtbASAinic7O2mJiB8APcBXgO2SbpI0LxU9F1gGPCbpnyWdmeKLgD9Kl8SelfQs0AocGxFbgT8E/ldq79aJS3Bm9vLi5HLge4IsIQAg6VVkl7PGACLiSxFxGrCE7PLYH6f4TyJiBfBa4O+B21ITo8BnI+Lw3OuVEfGtVO+bEfHW9JkBXDMTB2lmjcXJ5cBziKRXTLyAbwEXSjpF0hzgz4G7IuJRSZ2S3izpEOA/gF8Av5bULOmDkg6LiF8CzwG/Tu3/DXBpqidJr5L03yW9WlK7pLPT5/wC+M9cPTN7GXFyOfDcSfYf9YnX24E/Bb4DPAn8BnBeKjuPLFk8Q3bp7GngurTv94BHJT0HXEo2d0NEDAIXk11OewbYClyQ6swBPgf8DHiK7KznU/U4SDNrbPLDwszMrGg+czEzs8I5uZiZWeGcXMzMrHBOLmZmVrim2e7ATDnyyCNj8eLFs90NO0DdfffdP4uIBbPx2R7bVk+1ju2XTXJZvHgxg4ODs90NO0BJemzqUvXhsW31VOvY9mUxMzMrnJOLmZkVzsnFzMwK5+RiVqP+/n7a29splUoAR1ful3R5euDaJknrJC2q2D9P0jZJPVXq9kp6oH69N6svJxezGpTLZbq7u+nr62NoaAhgvqQlFcXuAToi4iRgDXBtxf6rgB9Vti3pt4Hn69Btsxnj5GJWg4GBAUqlEm1tbTQ3NwPsBFbky0TE+ojYld5uABZO7JN0GnAU8I/5OpLmApcDV9ex+2Z15+RiVoOxsTFaW1vzoXGgZQ9VLgL6ACQdBNwAfKJKuavSvl1V9r1A0iWSBiUN7tixY2+6bjYjnFzM6kzS+UAHLz7O4DLgzojYVlHuFOA3IuK7U7UZETdFREdEdCxYMCvf3TTbo5fNlyjNitTS0sLo6Gg+1Ex6umeepHOAK4C3RcTuFD4TOEvSZcBcoFnS82TP1OmQ9CjZ3+ZrJf0wIt5etwMxqxMnF7MadHZ2Mjw8zMjICC0tLQDzgd58GUmnAjcCSyNi+0Q8Ij6YK3MB2aT/qhT6aoovBv6PE4vtr5xczGrQ1NRET08PXV1dlMtlgJ0RsVnSlcBgRPSSXQabC9wuCeDxiFg+e702mzkvmydRdnR0hNdfsnqRdHdEdMzGZ3tsWz3VOrY9oW9mZoVzcjEzs8I5uZiZWeGcXMzMrHBOLmZmVjgnFzMzK5yTi5mZFc7JxczMCufkYmZmhXNyMTOzwjm5mJlZ4ZxczMyscE4uZmZWOCcXMzMrnJOLmZkVzsnFzMwK5+RiVqP+/n7a29splUoAR1ful3S5pCFJmyStk7SoYv88Sdsk9aT3r5R0h6SHJG2W9LmZORKz4jm5mNWgXC7T3d1NX18fQ0NDAPMlLakodg/QEREnAWuAayv2XwX8qCJ2fUS8ATgVeIukd9eh+2Z15+RiVoOBgQFKpRJtbW00NzcD7ARW5MtExPqI2JXebgAWTuyTdBpwFPCPufK7ImJ92h4HNubrmO1PnFzMajA2NkZra2s+NA607KHKRUAfgKSDgBuAT0xWWNLhwHuAdZPsv0TSoKTBHTt27GXvzerPycWsziSdD3QA16XQZcCdEbFtkvJNwLeAL0XEI9XKRMRNEdERER0LFiyoR7fN9knTbHfAbH/U0tLC6OhoPtQMjFWWk3QOcAXwtojYncJnAmdJugyYCzRLej4iVqX9NwHDEfGFuh2AWZ05uZjVoLOzk+HhYUZGRmhpaQGYD/Tmy0g6FbgRWBoR2yfiEfHBXJkLyCb9V6X3VwOHAR+p+0GY1ZGTi1kNmpqa6Onpoauri3K5DLAzIjZLuhIYjIhesstgc4HbJQE8HhHLJ2tT0kKys5yHgI2pTk9EfK3Oh2NWOEXEbPdhRnR0dMTg4OBsd8MOUJLujoiO2fhsj22rp1rHtif0zcyscE4uZmZWOCcXMzMrnJOLmZkVbsrkIukVkgYk3ZcW0/tMit+cYpskrZE0N1fnfWnBvs2SvpmLr5Q0nF4rc/HTJN0vaaukLyndJiNpvqS1qfxaSUekuFK5renz31TkD8XMzPbNdM5cdgNnR8TJwCnAUklnAB+PiJPTonyPAx8DkHQ88CngLRHxRuAPU3w+8GngzcDpwKcnkgXwVeBi4Pj0Wpriq4B1EXE82TIYE18ye3eu7CWpvpmZNYgpk0tknk9vD0mviIjnIDuLAA4FJu5pvhj4SkQ8k+pPfHmsC1gbETvTvrVkieoYYF5EbIjsvuhbgPemOiuA1Wl7dUX8ltS3DcDhqR0zM2sA05pzkXSwpHuB7WQJ4q4U/wbwFPAG4Mup+OuB10v6f5I2SJo4C2kB8utlbEuxlrRdGQc4KiKeTNtPka0iu6e2Kvvtxf3MzGbBtJJLRJQj4hSy5b9Pl3Riil8IHAs8CLw/FW8iu1z1duADwN+kFV73STqr2atvfHpxPzOz2bFXd4tFxLPAel6cEyEiysCtwLkptA3ojYhfRsQI8FOyZDMG5NcoX5hiY7z0mRUTcYB/m7jclf6duMQ2WVtmZtYApnO32IKJMw9JhwLvBLZIKqWYgOVk6yEB/D3ZWQuSjiS7TPYI8H3gXZKOSBP57wK+ny57PSfpjNTWh4DvpbZ6gYm7ylZWxD+U7ho7A/h57vKZmZnNsuksXHkMsFrSwWTJ6DbgDuDHkuYBAu4DPprKTySRIaAM/HFEPA0g6SrgJ6nclRGxM21fBvwt2Y0BfekF8DngNkkXAY8B70vxO4FlwFZgF3Dh3h22mZnVkxeuNCuAF660A5UXrjQzs4bh5GJmZoVzcjGrUX9/P+3t7ZRKJYCjK/dLujwtg7RJ0jpJiyr2z5O0TVJPLlZ1KSSz/Y2Ti1kNyuUy3d3d9PX1MTQ0BDBf0pKKYveQPcL4JGANcG3F/quAH1XEJlsKyWy/4uRiVoOBgQFKpRJtbW00NzcD7CRblugFEbE+InaltxvIfZ9L0mlkK078Yy62p6WQzPYrTi5mNRgbG6O1Nf89XsapsgRRzkWkW+wlHQTcAHyiosyelkIy269M53suZrYPJJ0PdABvS6HLgDsjYlutUyqSLiFbEZzjjjuuiG6aFcrJxawGLS0tjI7m106lmSpLEEk6B7gCeFtE7E7hM4GzJF0GzAWaJT0PfJHJl0J6iYi4CbgJsu+57NvRmBXPycWsBp2dnQwPDzMyMkJLSwvAfLJliV4g6VTgRmBp7tETRMQHc2UuIJv0X5XeP5eWNLqLbCmkL2O2H3JyMatBU1MTPT09dHV1US6XAXZGxGZJVwKDEdELXEd2ZnJ7uvz1eEQsn6LpyZZCMtuvePkXswJ4+Rc7UHn5FzMzaxhOLmZmVjgnFzMzK5yTi5mZFc7JxczMCufkYmZmhXNyMTOzwjm5mJlZ4ZxczMyscE4uZmZWOCcXMzMrnJOLmZkVzsnFzMwK5+RiZmaFc3IxM7PCObmYmVnhnFzMatTf3097ezulUgng6Mr9ki6XNCRpk6R1khal+CJJGyXdK2mzpEtzdT4g6f5Up1/SkTN3RGbFcXIxq0G5XKa7u5u+vj6GhoYA5ktaUlHsHqAjIk4C1gDXpviTwJkRcQrwZmCVpGMlNQFfBH4r1dkEfGwmjsesaE4uZjUYGBigVCrR1tZGc3MzwE5gRb5MRKyPiF3p7QZgYYqPR8TuFJ/Di3+HSq9XSRIwD3iivkdiVh9OLmY1GBsbo7W1NR8aB1r2UOUioG/ijaRWSZuAUeCaiHgiIn4JfBS4nyypLAFurtaYpEskDUoa3LFjx74djFkdOLmY1Zmk84EO4LqJWESMpktfJWClpKMkHUKWXE4FjiW7LPapam1GxE0R0RERHQsWLKj7MZjtLScXsxq0tLQwOjqaDzUDY5XlJJ0DXAEsz10Ke0FEPAE8AJwFnJJiD0dEALcB/6343pvVn5OLWQ06OzsZHh5mZGSE8fFxgPlAb76MpFOBG8kSy/ZcfKGkQ9P2EcBbgS1kyWmJpIlTkXcCD9b9YMzqoGm2O2C2P2pqaqKnp4euri7K5TLAzojYLOlKYDAieskug80Fbs/m53k8IpYDJwA3SAqyCfzrI+J+AEmfAX4k6ZfAY8AFM31sZkVQdvZ94Ovo6IjBwcHZ7oYdoCTdHREds/HZHttWT7WObV8WMzOzwjm5mJlZ4aZMLpJeIWlA0n1pqYrPpPjNKbZJ0hpJcyvqnSspJHXkYp+StFXSFkldufjSFNsqaVUu/jpJd6X4tyU1p/ic9H5r2r94338UZmZWlOmcuewGzo6Ik8lulVwq6Qzg4xFxcrpX/3Fyy1RIejXwB8BdudgS4DzgjcBS4K8kHSzpYOArwLvJvjT2gdwyGtcAn4+IEvAM2RfRSP8+k+KfT+XMzKxBTJlcIvN8entIekVEPAeQlqk4FMjfGXAV2X/wf5GLrQBujYjdETECbAVOT6+tEfFIRIwDtwIrUrtnk63JBLAaeG+urdVpew3wjlTezMwawLTmXNIZxr3AdmBtRNyV4t8AngLeAHw5xd4EtEbEHRXNtJAtdTFhW4pNFn8N8GxE/Koi/pK20v6fp/KV/fYSGWZms2BaySUiymkF14XA6ZJOTPELyZapeBB4v6SDgL8E/qhO/d0rXiLDzGx27NXdYhHxLLCebM5kIlYmu5R1LvBq4ETgh5IeBc4AetOk/hiQX+lvYYpNFn8aODwtQ56Pk6+T9h+WypuZWQOYzt1iCyQdnrYPJVuSYoukUooJWA48FBE/j4gjI2JxRCwmW2Z8eUQMki2NcV660+t1wPHAAPAT4Ph0Z1gz2aR/b1pbaT3wO6krK4Hvpe3e9J60/wfxcvk2qJnZfmA6y78cA6xOd3UdRLaY3h3AjyXNI1u+4j6y1VwnlZbGuA0YAn4FdKezHiR9DPg+cDDw9YjYnKp9ErhV0tVkD16aWH78ZuDvJG0le47GedM8XjMzmwFTJpeI2ES2BHilt0yj7tsr3n8W+GyVcncCd1aJP0J2N1ll/BfA7071+WZmNjv8DX0zMyuck4uZmRXOycXMzArn5GJmZoVzcjEzs8I5uZjVqL+/n/b2dkqlEsDRlfslXS5pKK0cvk7SohRfJGmjpHvTSuOX5uo0S7pJ0k8lPSTp3Jk7IrPi+DHHZjUol8t0d3ezdu1aFi5cyJw5c+ZLWhIRQ7li9wAdEbFL0keBa4H3A08CZ0bE7vSoigck9UbEE8AVwPaIeH1aTmn+TB+bWRGcXMxqMDAwQKlUoq2tbSK0k2y17heSS0Ssz1XZAJyf4uO5+BxeegXhw2QLwRIRvwZ+VnjnzWaAL4uZ1WBsbIzW1vySeIzz4qrd1VwE9E28kdQqaRPZ6t7XRMQTE8ssAVely2a3SzqqWmNe8dsanZOLWZ1JOh/oAK6biEXEaHrQXglYmZJIE9kCrf8SEW8C/hW4vlqbXvHbGp2Ti1kNWlpaGB3NP4aIZl5ctfsFks4hm0dZHhG7K/eneZYHgLPIVvbeBfzvtPt24E3F9txsZji5mNWgs7OT4eFhRkZGGB8fh2zivTdfRtKpwI1kiWV7Lr4wrTCOpCOAtwJb0sre/wC8PRV9B7k5HLP9iSf0zWrQ1NRET08PXV1dlMtlgJ1p5e8rgcGI6CW7DDYXuD09hfvxiFgOnADcICnIVhW/PiLuT01/kmzF7y8AO4ALZ/bIzIqhl8tjUDo6OmJwcHC2u2EHKEl3R0THbHy2x7bVU61j25fFzMyscE4uZmZWOCcXMzMrnJOLmZkVzsnFzMwK5+RiZmaFc3IxM7PCObmYmVnhnFzMzKxwTi5mZlY4JxczMyuck4uZmRXOycXMzArn5GJmZoVzcjEzs8I5uZiZWeGcXMxq1N/fT3t7O6VSCeDoyv2SLpc0JGmTpHWSFqX4IkkbJd0rabOkS6vU7ZX0QP2Pwqw+nFzMalAul+nu7qavr4+hoSGA+ZKWVBS7B+iIiJOANcC1Kf4kcGZEnAK8GVgl6diJSpJ+G3i+7gdhVkdOLmY1GBgYoFQq0dbWRnNzM8BOYEW+TESsj4hd6e0GYGGKj0fE7hSfQ+7vUNJc4HLg6jofglldObmY1WBsbIzW1tZ8aBxo2UOVi4C+iTeSWiVtAkaBayLiibTrKuAGYNd/beJFki6RNChpcMeOHbUcglldObmY1Zmk84EO4LqJWESMpstlJWClpKMknQL8RkR8d6o2I+KmiOiIiI4FCxbUre9mtWqa7Q6Y7Y9aWloYHR3Nh5qBscpyks4BrgDelrsU9oKIeCJN3J8FLAA6JD1K9rf5Wkk/jIi3F38EZvXlMxezGnR2djI8PMzIyAjj4+MA84HefBlJpwI3AssjYnsuvlDSoWn7COCtwJaI+GpEHBsRi1Psp04str/ymYtZDZqamujp6aGrq4tyuQywMyI2S7oSGIyIXrLLYHOB2yUBPB4Ry4ETgBskBSDg+oi4f3aOxKw+FBF7LiC9AvgR2V0tTcCaiPi0pJvJriML+ClwQUQ8L+ly4CPAr4AdwIcj4rHU1krgT1LTV0fE6hQ/Dfhb4FDgTuAPIiIkzQe+DSwGHgXeFxHPKPtL/SKwjGzi84KI2Lin4+jo6IjBwcHp/lzM9oqkuyOiYzY+22Pb6qnWsT2dy2K7gbMj4mTgFGCppDOAj0fEyWlS8nHgY6l81Xv7U6L4NNl9/acDn06XBAC+ClwMHJ9eS1N8FbAuIo4H1qX3AO/Olb0k1TczswYxZXKJzMQXug5Jr4iI5wDSWcShQKTyVe/tB7qAtRGxMyKeAdaSJapjgHkRsSGy06hbgPemOiuA1Wl7dUX8ltS3DcDhqR0zM2sA05rQl3SwpHuB7WQJ4q4U/wbwFPAG4MtVqubv7W8hu6d/wrYUa0nblXGAoyLiybT9FHDUFG1V9tvfBTAzmwXTSi4RUU5LVSwETpd0YopfCBwLPAi8P1+n2r39+yKd1ex5gui/1vF3AczMZsFe3YocEc8C63lxToSIKAO3AudOxHL39i/P3ds/BuS/0rwwxcZ48dJZPg7wbxOXu9K/E7dzTtaWmZk1gCmTi6QFkg5P24cC7wS2SCqlmIDlwEPpfdV7+4HvA++SdESayH8X8P102es5SWektj4EfC/V6QVWpu2VFfEPKXMG8PPc5TMzM5tl0/meyzHAakkHkyWj24A7gB9Lmkd2K/J9wEdT+ar39kfETklXAT9J5a6MiJ1p+zJevBW5jxfnaT4H3CbpIuAx4H0pfifZbchbyW5FvnAvj9vMzOpoyuQSEZuAU6vsessk5c/ZQ1tfB75eJT4InFgl/jTwjirxALon77WZmc0mL/9iZmaFc3IxM7PCObmYmVnhnFzMzKxwTi5mZlY4JxczMyuck4uZmRXOycXMzArn5GJWo/7+ftrb2ymVSgBHV+6XdLmkIUmbJK2TtCjFF0naKOleSZslXZrir5R0h6SHUvxzM3tEZsVxcjGrQblcpru7m76+PoaGhgDmS1pSUazqg/OAJ4Ez00rjbwZWSTo27bs+It5AtirGWyS9u+4HY1YHTi5mNRgYGKBUKtHW1kZzczPATrKH2L1gsgfnRcR4brXwOaS/w4jYFRHrJ8oAG3npiuFm+w0nF7MajI2N0dqaf+oD41R5YF1O/sF5SGqVtInsoXfXRMQT+cJpJfL3kD3e+7/wg/Cs0Tm5mNVZtQfnRcRoulxWAlZKOipXvgn4FvCliHikWpt+EJ41OicXsxq0tLQwOpp/0jbNVHlg3SQPzntBOmN5ADgrF74JGI6ILxTaabMZ5ORiVoPOzk6Gh4cZGRlhfHwcYD7ZQ+xeMNmD8yQtTA/eIz04763AlvT+auAw4A9n5EDM6mQ6DwszswpNTU309PTQ1dVFuVwG2BkRmyVdCQxGRC+TPDgPOAG4QVKQPWzv+oi4X9JCsrOch4CNqU5PRHxtxg/QbB85uZjVaNmyZSxbtgwASU8BRMSfTeyf7MF5EbEWOKlKfBtZsjHb7/mymJmZFc7JxczMCufkYmZmhXNyMTOzwjm5mJlZ4ZxczMyscE4uZmZWOCcXMzMrnJOLmZkVzsnFzMwK5+RiZmaFc3IxM7PCObmYmVnhnFzMzKxwTi5mZlY4JxczMyuck4tZjfr7+2lvb6dUKgEcXblf0uWShiRtkrRO0qIUXyRpo6R7JW2WdGmuzmmS7pe0VdKXlB5Haba/cXIxq0G5XKa7u5u+vj6GhoYA5ktaUlHsHqAjIk4C1gDXpviTwJkRcQrwZmCVpGPTvq8CFwPHp9fSOh+KWV04uZjVYGBggFKpRFtbG83NzQA7gRX5MhGxPiJ2pbcbgIUpPh4Ru1N8DunvUNIxwLyI2BARAdwCvLf+R2NWPCcXsxqMjY3R2tqaD40DLXuochHQN/FGUqukTcAocE1EPJHqb8vV2TZZm5IukTQoaXDHjh01HoVZ/Ti5mNWZpPOBDuC6iVhEjKbLZSVgpaSj9qbNiLgpIjoiomPBggXFdtisAFMmF0mvkDQg6b40+fiZFL85xTZJWiNpborPkfTtNCF5l6TFubY+leJbJHXl4ktTbKukVbn461IbW1ObzVN9htlMaGlpYXR0NB9qBsYqy0k6B7gCWJ67FPaCdMbyAHBWqr8wt3thtTbN9gfTOXPZDZwdEScDpwBLJZ0BfDwiTk7/9/U48LFU/iLgmYgoAZ8HrgFIk53nAW8km6T8K0kHSzoY+ArwbmAJ8IHcxOg1wOdTW8+ktif9DLOZ0tnZyfDwMCMjI4yPjwPMB3rzZSSdCtxIlli25+ILJR2ato8A3gpsiYgngecknZHuEvsQ8L2ZOSKzYk2ZXCLzfHp7SHpFRDwHkP4IDgUilVkBrE7ba4B3pDIrgFsjYndEjABbgdPTa2tEPBIR48CtwIpU5+zUBqnN907xGWYzoqmpiZ6eHrq6ujjhhBMAdkbEZklXSlqeil0HzAVuT7cdTySfE4C7JN0H/DNwfUTcn/ZdBnyN7O/jYXLzNGb7k6bpFEpnF3eTXR/+SkTcleLfAJYBQ8AfpeItZJOURMSvJP0ceE2Kb8g1m5+sHK2IvznVeTYiflWl/GSf8bOKfl8CXAJw3HHHTedQzaZt2bJlLFu2DABJTwFExJ9N7I+Ic6rVi4i1wEmT7BsETiy8s2YzbFoT+hFRTvfkLwROl3Riil8IHAs8CLy/br2skSc9zcxmx17dLRYRzwLryX2xKyLKZJeyzk2hMaAVQFITcBjwdD6eTExWThZ/Gjg8tZGP7+kzzMysAUznbrEFkg5P24cC7wS2SCqlmIDlwEOpSi+wMm3/DvCD9IWwXuC8dKfX68i+fTwA/AQ4Pt0Z1kw26d+b6qxPbZDa/N4Un2FmZg1gOnMuxwCr07zLQcBtwB3AjyXNAwTcB3w0lb8Z+DtJW8m+tXweQJrsvI1sfuZXQHc660HSx4DvAwcDX4+IzamtTwK3SrqabCmNm/f0GWZm1himTC4RsQk4tcqut0xS/hfA706y77PAZ6vE7wTurBJ/hOxusml/hpmZzT5/Q9/MzArn5GJmZoVzcjEzs8I5uZiZWeGcXMzMrHBOLmZmVjgnFzMzK5yTi5mZFc7JxczMCufkYmZmhXNyMTOzwjm5mNWov7+f9vZ2SqUSwNGV+yVdLmlI0iZJ6yQtSvFTJP2rpM1p3/tzdd4haWN6cuX/nVh93Gx/4+RiVoNyuUx3dzd9fX0MDQ0BzJe0pKLYPUBHRJxE9jjua1N8F/ChiHgj2bORvjDxWAvgq8AH08P5vgn8Sb2PxawenFzMajAwMECpVKKtrY3m5mbIHv2wIl8mItZHxK70dgPZA++IiJ9GxHDafgLYDkw8KjWAeWn7MOCJuh6IWZ1M53kuZlZhbGyM1tb8A1QZB1r2UOUioK8yKOl0oBl4OIU+Atwp6T+B54AzqjUm6RLgEoDjjjtub7tvVnc+czGrM0nnAx3AdRXxY4C/Ay6MiF+n8MeBZRGxEPgG8JfV2oyImyKiIyI6FixYUK2I2azymYtZDVpaWhgdHc2HmoGxynKSzgGuAN4WEbtz8XlkT3S9IiI2pNgC4OSIuCsV+zbQX58jMKsvn7mY1aCzs5Ph4WFGRkYYHx8HmA/05stIOhW4EVgeEdtz8Wbgu8AtEbEmV+UZ4DBJr0/v3wk8WMfDMKsbn7mY1aCpqYmenh66urool8sAOyNis6QrgcGI6CW7DDYXuF0SwOMRsRx4H/CbwGskXZCavCAi7pV0MfAdSb8mSzYfntkjMyuGImK2+zAjOjo6YnBwcLa7YQcoSXdHRMdsfLbHttVTrWPbl8XMzKxwTi5mZlY4JxczMyuck4uZmRXOycXMzAr3srlbTNIO4LFJdh8J/GwGu7MnjdKXRukHNE5f9tSPRRExK1+V30/GdqP0AxqnL43SD6jD2H7ZJJfYQ0reAAAFGUlEQVQ9kTQ4W7eRVmqUvjRKP6Bx+tIo/dgbjdLnRukHNE5fGqUfUJ+++LKYmZkVzsnFzMwK5+SSuWm2O5DTKH1plH5A4/SlUfqxNxqlz43SD2icvjRKP6AOffGci5mZFc5nLmZmVjgnFzMzK9wBnVwkzZe0VtJw+veIScqtTGWGJa3MxX8oaYuke9PrtSk+R9K3JW2VdJekxfXqh6RXSrpD0kOSNkv6XK78BZJ25Pr3kT30YWk6lq2SVlXZP+kxSfpUim+R1DXdNovsh6R3Srpb0v3p37Nzdar+nurYl8WS/jP3eX+dq3Na6uNWSV9SWmu/SI0yrve1L0WM7UYZ1/vSl6LHdsOM64g4YF/AtcCqtL0KuKZKmfnAI+nfI9L2EWnfD4GOKnUuA/46bZ8HfLte/QBeCfxWKtMM/Bh4d3p/AdAzjZ/DwWTPaG9LbdwHLJnOMQFLUvk5wOtSOwdPp82C+3EqcGzaPhEYy9Wp+nuqY18WAw9M0u4A2XPvBfRN/K4OxHE922O7UcZ1I43tRhrXB/SZC7ACWJ22VwPvrVKmC1gbETsj4hlgLbB0L9pdA7xjikxecz8iYldErAeIiHFgI7Bwiv5VOh3YGhGPpDZuTX2azjGtAG6NiN0RMQJsTe1Np83C+hER90TEEym+GThU0pxp/wQK7MtkDUo6BpgXERsi+4u8heq/633VKON6n/pSwNhulHG9T30peGw3zLg+0JPLURHxZNp+CjiqSpkWIP8w9G0pNuEb6RTxT3O/gBfqRMSvgJ8Dr6lzP5B0OPAeYF0ufK6kTZLWSGqd5POnbJvJj2myutNps8h+5J0LbIzcM+mp/nuqZ19eJ+keSf8s6axc+W1TtFmERhnXRfWl1rHdKON6X/uSt69ju2HG9X7/mGNJ/wQcXWXXFfk3ERGS9va+6w9GxJikVwPfAX6PLGtX8x1J1f4Qi+gHkpqAbwFfiohHUvgfgG9FxG5Jv0/2fyNnT9bGgUDSG4FrgHflwnvzeyrCk8BxEfG0pNOAv0/9KkwDjet698VjO2mAsV3ouN7vk0tEnDPZPkn/JumYiHgyndptr1JsDHh77v1CsuucRMRY+vffJX2T7JTzllSnFdiW/jAOA0rplLHwfiQ3AcMR8YWJQEQ8ndv/NbLr39VM9Dff9tgkZfLH9PQUdadqs8h+IGkh8F3gQxHx8ESFPfye6tKX9HvenT7zbkkPA69P5fOXdabzM6mqgcb10/XsS1Lr2G6Ucb2vfSlybDfOuJ5qUmZ/fgHX8dLJxmurlJkPjJBNMB6RtueTJd4jU5lDyK5NXpred/PSCbHb6tWPtO9qsv9rOaiizjG57f8JbJjk85vIJlFfx4uTfG+sKFP1mIA38tKJz0fIJg2nbLPgfhyeyv92lTar/p7q2JcFwMFpu43sD23id1U58bnsQB3Xsz22G2VcN9LYbqRxXbf/sDfCi+w64jpgGPin3A+qA/hartyHySb0tgIXptirgLuBTWSTbF/M/eBfAdyeyg8AbXXsx0IggAeBe9PrI2nfX6S+3QesB96whz4sA35KdifJFSl2JbB8qmMiu/zxMLCF3F0i1dqcxu+kpn4AfwL8R+5ncC/w2j39nurYl3PTZ91LNgn9nlybHcADqc0e0ioYB+K4boSxXevvsOhx3Uhjex/6Uei49vIvZmZWuAP9bjEzM5sFTi5mZlY4JxczMyuck4uZmRXOycXMzArn5GJmZoVzcjEzs8L9f/CV1R/z7eIUAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 432x288 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import pickle\n",
    "\n",
    "with open('stats.st', 'rb') as statfile:\n",
    "    statistic = pickle.load(statfile)\n",
    "    \n",
    "#print(statistic)\n",
    "\n",
    "#trainer.plot_over_epoch()\n",
    "from trainer import VQATrainer\n",
    "\n",
    "trainer = VQATrainer(None, None)\n",
    "trainer.statistics = statistic\n",
    "\n",
    "trainer.plot_over_epoch()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:16:27.638069Z",
     "start_time": "2018-07-12T16:16:25.345475Z"
    }
   },
   "outputs": [],
   "source": [
    "from torchvision import transforms\n",
    "import matplotlib.pyplot as plt\n",
    "import random\n",
    "\n",
    "\n",
    "device = torch.device('cuda')\n",
    "vocab_size = len(vocab)\n",
    "model = ConcatNet(vocab_size).to(device)\n",
    "\n",
    "state_dict = torch.load('model_epoch4.pt')\n",
    "model.load_state_dict(state_dict)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-12T16:20:11.295269Z",
     "start_time": "2018-07-12T16:20:10.416459Z"
    }
   },
   "outputs": [],
   "source": [
    "import random\n",
    "\n",
    "for idx in [random.randint(0, 8) for i in range(8)]:\n",
    "    print('\\nqn no', idx)\n",
    "    qns, img, ans = collate([train_dataset[idx]])\n",
    "    output = model(img.cuda(), qns.long().cuda())\n",
    "    _, pred = output.topk(10)\n",
    "    # print(qns, pred)\n",
    "\n",
    "    #pil_img = transforms.ToPILImage()(img)\n",
    "    #plt.imshow(pil_img)\n",
    "    qnss = ' '.join([vocab.idx2word[i.item()] for i in qns.data])\n",
    "    ans_ = ' / '.join([answers.idx2ans[j.item()] for j in pred[0]])\n",
    "    lbl = ' - '.join([answers.idx2ans[k.item()] for k in ans[0]])\n",
    "    print('question:', qnss)\n",
    "    print('answer:', ans_)\n",
    "    print('label:', lbl)\n",
    "    ans = [a.cuda() for a in ans]\n",
    "    print('accuracy', trainer.accuracy_fn(output.detach(), ans))\n",
    "    print('loss', trainer.get_losses(output, ans))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": false,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
